from django.urls import path
from . import views

app_name = "adm"
urlpatterns = [
    path("admin", views.AdminView.as_view(template_name="adm/admin.html"), name="admin"),
    path("users", views.AdminUsersView.as_view(template_name="adm/users.html"), name="users"),
    path("user_create", views.AdminUserCreateView.as_view(template_name="adm/user_create.html"), name="user_create"),
    path("user_update/<int:id>", views.AdminUserUpdateView.as_view(template_name="adm/user_update.html"), name="user_update"),
    path("user_delete/<int:id>", views.AdminUserDeleteView.as_view(), name="user_delete"),
    path("jobs", views.AdminJobsView.as_view(template_name="adm/jobs.html"), name="jobs"),
    path("job_create", views.AdminJobCreateView.as_view(template_name="adm/job_create.html"), name="job_create"),
    path("job_update/<int:id>", views.AdminJobUpdateView.as_view(template_name="adm/job_update.html"), name="job_update"),
    path("job_delete/<int:id>", views.AdminJobDeleteView.as_view(), name="job_delete"),
    path("marks", views.AdminMarksView.as_view(template_name="adm/marks.html"), name="marks"),
    path("mark_create", views.AdminMarkCreateView.as_view(template_name="adm/mark_create.html"), name="mark_create"),
    path("mark_update/<int:id>", views.AdminMarkUpdateView.as_view(template_name="adm/mark_update.html"), name="mark_update"),
    path("mark_delete/<int:id>", views.AdminMarkDeleteView.as_view(), name="mark_delete"),
    path("vehicles", views.AdminVehiclesView.as_view(template_name="adm/vehicles.html"), name="vehicles"),
    path("vehicle_create", views.AdminVehicleCreateView.as_view(template_name="adm/vehicle_create.html"), name="vehicle_create"),
    path("vehicle_update/<int:id>", views.AdminVehicleUpdateView.as_view(template_name="adm/vehicle_update.html"), name="vehicle_update"),
    path("vehicle_delete/<int:id>", views.AdminVehicleDeleteView.as_view(), name="vehicle_delete"),
    path("insurances", views.AdminInsurancesView.as_view(template_name="adm/insurances.html"), name="insurances"),
    path("insurance_create", views.AdminInsuranceCreateView.as_view(template_name="adm/insurance_create.html"), name="insurance_create"),
    path("insurance_update/<int:id>", views.AdminInsuranceUpdateView.as_view(template_name="adm/insurance_update.html"), name="insurance_update"),
    path("insurance_delete/<int:id>", views.AdminInsuranceDeleteView.as_view(), name="insurance_delete"),
    path("branches", views.AdminBranchesView.as_view(template_name="adm/branches.html"), name="branches"),
    path("branch_create", views.AdminBranchCreateView.as_view(template_name="adm/branch_create.html"), name="branch_create"),
    path("branch_update/<int:id>", views.AdminBranchUpdateView.as_view(template_name="adm/branch_update.html"), name="branch_update"),
    path("branch_delete/<int:id>", views.AdminBranchDeleteView.as_view(), name="branch_delete"),
    path("employees", views.AdminEmployeesView.as_view(template_name="adm/employees.html"), name="employees"),
    path("employee_create", views.AdminEmployeeCreateView.as_view(template_name="adm/employee_create.html"), name="employee_create"),
    path("employee_update/<int:id>", views.AdminEmployeeUpdateView.as_view(template_name="adm/employee_update.html"), name="employee_update"),
    path("employee_delete/<int:id>", views.AdminEmployeeDeleteView.as_view(), name="employee_delete"),
]